spring.application.name=spotify


# CONFIGURACAO POSTGRES

spring.datasource.url=jdbc:postgresql://aps-projeto2-progeficaz-ebg.i.aivencloud.com:20711/defaultdb?ssl=require
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# CONFIGURACOES GERAIS

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.main.allow-bean-definition-overriding=true